---
name: ci

on:
  push:
    branches:
      - main
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    - cron: 0 18 * * *

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          show-progress: false
      - uses: gradle/actions/setup-gradle@v5
      - name: set-up-jdk
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: check-java
        run: java --version

      - name: Install Uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: "rewrite/.python-version"

      - name: Install dependencies
        working-directory: rewrite
        run: |
          uv sync --all-extras

#      - name: Run tests
#        run: |
#          poe test

      - name: build-python
        working-directory: rewrite
        run: |
          uv build
          uv pip install -e .

      - name: build-java
        run: ./gradlew ${{ env.GRADLE_SWITCHES }} build

      - name: publish-snapshots
        if: github.event_name != 'pull_request'
        run: ./gradlew ${{ env.GRADLE_SWITCHES }} snapshot publish -PforceSigning -x test
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_TOKEN }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.OSSRH_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.OSSRH_SIGNING_PASSWORD }}
